version: '3.8'

services:
  # Base de Datos PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    container_name: ares_postgres
    environment:
      POSTGRES_DB: ares_colony_db
      POSTGRES_USER: astronauta
      POSTGRES_PASSWORD: marte_password
    ports:
      - "5432:5432"

  # Servicio Climático en Python
  cerebro-python:
    build: ./climaService
    container_name: cerebro_python
    ports:
      - "5000:5000"

  # Backend Central en Java Spring Boot
  hub-java:
    build: ./HubBackEnd
    container_name: hub_java
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - cerebro-python
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/ares_colony_db
      SPRING_DATASOURCE_USERNAME: astronauta
      SPRING_DATASOURCE_PASSWORD: marte_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update